offchain/Cargo.lock
offchain/Cargo.toml
offchain/authority-claimer/Cargo.toml
offchain/authority-claimer/src/checker.rs
offchain/authority-claimer/src/claimer.rs
offchain/authority-claimer/src/config/cli.rs
offchain/authority-claimer/src/config/error.rs
offchain/authority-claimer/src/config/json.rs
offchain/authority-claimer/src/config/mod.rs
offchain/authority-claimer/src/lib.rs
offchain/authority-claimer/src/listener.rs
offchain/authority-claimer/src/main.rs
offchain/authority-claimer/src/metrics.rs
offchain/authority-claimer/src/sender.rs
offchain/http-server/src/config.rs
offchain/http-server/src/lib.rs

This is mostly code imported from the dispatcher.
Had to do some code massaging to fit Rust's restrictions when using traits.

feat(offchain): adds the authority-claimer

---

CHANGELOG.md
cmd/cartesi-rollups-cli/root/read/read.go
cmd/cartesi-rollups-cli/root/read/report/report.go
cmd/cartesi-rollups-cli/root/read/reports/reports.go
pkg/readerclient/generate/input_reports.graphql
pkg/readerclient/generate/report.graphql
pkg/readerclient/generate/reports.graphql
pkg/readerclient/generated.go
pkg/readerclient/genqlient.yaml
pkg/readerclient/report.go

Add read report commands to rollups-cli

---

build/node-compose.yml
cmd/cartesi-rollups-node/services.go

When executing the cartesi-rollups-node in a docker container, using the address 127.0.0.1 blocks services from receiving connections from interfaces outside the container. This prevents users from interacting with the Host Runner or querying the GraphQL and Inspect servers.
This commit also fixes the port mapping for GraphQL and Inspect servers in the node-compose.yml file
---
**Obs:** I've only changed the IP addresses of the services that need to receive connections from outside the container. I'm unsure of what is best: to make the difference apparent or to standardize it all.
@GMKrieger thank you for the help in understanding what was going on.

fix: service reachability

---

pkg/readerclient/generate/input.graphql
pkg/readerclient/generate/inputs.graphql
pkg/readerclient/generated.go
pkg/readerclient/input.go

#209 
Due to the way the structs are made for the other queries, there's a small redundancy as the input index is repeated several times. Since this is a debug tool, I left this as is.

Update read input(s) command

---

cmd/gen-docs/main.go

Small change so we can run `go generate` to generate the cli docs

chore: generate cli docs with go generate command

---

cmd/cartesi-rollups-node/main.go
cmd/cartesi-rollups-node/services.go
docs/config.md
internal/config/generate/Config.toml
internal/config/get.go
internal/services/http.go
internal/services/http_test.go
internal/services/supervisor_test.go

Add external healthcheck to `cartesi-rollups-node`

---

CHANGELOG.md
cmd/cartesi-rollups-cli/root/root.go
cmd/cartesi-rollups-cli/root/validate/validate.go
docs/cartesi-rollups-cli.md
docs/cartesi-rollups-cli_validate.md
pkg/ethutil/ethutil.go
pkg/readerclient/proof.go

Add validate notice command

---

internal/services/command.go
internal/services/linewriter.go
internal/services/linewriter_test.go

fix: multi-line logs in Go supervisor

---

CHANGELOG.md
offchain/dispatcher/src/dispatcher.rs
offchain/dispatcher/src/drivers/mock.rs
offchain/types/src/foldables.rs

Close #278 
I tested on Sepolia with Alchemy and it solves the issue.

fix: high RPC usage in dispatcher

---

CHANGELOG.md
cmd/cartesi-rollups-cli/root/execute/execute.go
cmd/cartesi-rollups-cli/root/root.go
docs/cartesi-rollups-cli.md
docs/cartesi-rollups-cli_execute.md
pkg/ethutil/ethutil.go

Add execute voucher command

---

build/compose-node.yaml
cmd/cartesi-rollups-cli/root/increasetime/increasetime.go
cmd/cartesi-rollups-cli/root/inspect/inspect.go
cmd/cartesi-rollups-cli/root/read/input/input.go
cmd/cartesi-rollups-cli/root/read/inputs/inputs.go
cmd/cartesi-rollups-cli/root/read/notice/notice.go
cmd/cartesi-rollups-cli/root/read/notices/notices.go
cmd/cartesi-rollups-cli/root/read/report/report.go
cmd/cartesi-rollups-cli/root/read/reports/reports.go
cmd/cartesi-rollups-cli/root/read/voucher/voucher.go
cmd/cartesi-rollups-cli/root/read/vouchers/vouchers.go
cmd/cartesi-rollups-cli/root/validate/validate.go
cmd/cartesi-rollups-node/handlers.go
cmd/cartesi-rollups-node/services.go
docs/cartesi-rollups-cli_increase-time.md
docs/cartesi-rollups-cli_inspect.md
docs/cartesi-rollups-cli_read_input.md
docs/cartesi-rollups-cli_read_inputs.md
docs/cartesi-rollups-cli_read_notice.md
docs/cartesi-rollups-cli_read_notices.md
docs/cartesi-rollups-cli_read_report.md
docs/cartesi-rollups-cli_read_reports.md
docs/cartesi-rollups-cli_read_voucher.md
docs/cartesi-rollups-cli_read_vouchers.md
docs/cartesi-rollups-cli_validate.md
internal/services/http.go

Modifies HttpService to act as a reverse proxy. Calls to /graphql, /inspect, /rollups, and /metrics endpoints are now received by it and forwarded to graphql-server, inspect-server, host-runner, and dispatcher respectively. The ports these services use needn't be exposed anymore, making HttpService the single access point to the node's APIs.
This is a step towards transforming these services into Golang modules.
Closes #241

feat: hide internal services behind proxy

---

.github/workflows/rust-code-quality.yml

This fixes the issues where some PRs are getting stuck because the access-rust-code-quality doesn't run.

fix(ci): always run Rust workflow

---

build/Dockerfile
cmd/gen-devnet/deployer.go
cmd/gen-devnet/main.go
cmd/gen-devnet/rollups.go

As a follow-up to #289:
- This removes an unnecessary dependency from internal/config. 
- 🐢 While here, also log anvil_state.json location.

feat(devnet): add verbose logging argument

---

CHANGELOG.md
cmd/cartesi-rollups-node/chainid.go
cmd/cartesi-rollups-node/chainid_test.go
cmd/cartesi-rollups-node/main.go
docs/config.md
internal/config/config.go
internal/config/generate/Config.toml
internal/config/get.go

Validate Chain ID

---

CHANGELOG.md
docs/config.md
internal/config/config.go
internal/config/generate/Config.toml
internal/config/get.go
internal/services/server-manager.go

A workaround so Sunodo can display only the application output on its log. Closes #345

feat: allow server-manager to bypass log config

---

CHANGELOG.md
cmd/cartesi-rollups-node/services.go
docs/config.md
internal/config/auth.go
internal/config/config.go
internal/config/generate/Config.toml
internal/config/get.go
offchain/authority-claimer/src/config/cli.rs
offchain/authority-claimer/src/config/mod.rs
offchain/authority-claimer/src/signer/signer.rs

This PR adds the option to specify CARTESI_AUTH_PRIVATE_KEY to pass to the authority-claimer in case the user have a simple private key in hand, and not a mnemonic.
The value of the private key must be a hex string of 32 bytes, without the traditional starting `0x`.
i.e.: `59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d`
closes #344

Support specification of private key to claimer

---

CHANGELOG.md
docs/config.md
internal/config/config.go
internal/config/generate/Config.toml
internal/config/get.go
internal/services/server-manager.go

Brings the changes introduced in version 1.3.1 to the main branch

Feat/rebase 1.3.1

---

docs/config.md
internal/node/config/generate/Config.toml
internal/node/config/generated.go

`CARTESI_CONTRACTS_INPUT_BOX_DEPLOYMENT_BLOCK_NUMBER` was registered in the wrong topic, making it appear out of place in the final Markdown file

docs: change configuration topic

---

cmd/authority-claimer/rust-toolchain.toml

Fix rust version at 1.77.0 to prevent unwanted issues. Rust version should be updated alongside Node Docker image generation

fix: fix Rust version at 1.77.0

---

.github/workflows/build.yml
build/docker-bake.hcl
cmd/authority-claimer/rust-toolchain.toml
cmd/authority-claimer/src/listener.rs
cmd/authority-claimer/src/sender.rs
cmd/authority-claimer/src/signer/mod.rs

Bum Rust to 1.78.0

---

offchain/authority-claimer/src/listener.rs

Similar to #438, it's going to cover the CI checks for #407

[1.4.x] remove dead code from claimer

---

cmd/cartesi-rollups-cli/root/app/add/add.go
docs/cli/cartesi-rollups-cli_app_add.md
internal/evmreader/evmreader.go
internal/evmreader/evmreader_test.go
internal/evmreader/inputsource_adapter.go
internal/evmreader/retrypolicy/retrypolicy_ethclient_delegator.go
internal/evmreader/retrypolicy/retrypolicy_ethwsclient_delegator.go
internal/evmreader/retrypolicy/retrypolicy_inputsource_delegator.go
internal/node/model/models.go
internal/repository/base.go
internal/repository/base_test.go
internal/repository/evmreader.go
internal/repository/evmreader_test.go
internal/repository/migrations/000001_create_application_input_claim_output_report_nodeconfig.down.sql
internal/repository/migrations/000001_create_application_input_claim_output_report_nodeconfig.up.sql
internal/repository/migrations/000002_create_postgraphile_view.up.sql
internal/repository/validator.go
internal/repository/validator_test.go

feat(database): Add Epoch and Snapshot tables

---

CHANGELOG.md
docs/config.md
internal/node/config/config.go
internal/node/config/config_test.go
internal/node/config/generate/Config.toml
internal/node/config/generated.go
internal/node/services.go

Reverts some of the changes made at #559 and add a sort of reader mode to better split the configuration in the case of the sunodo validator mode.

Add reader mode and revert unnecessary changes to sunodo validator mode

---

CHANGELOG.md
offchain/authority-claimer/README.md
offchain/authority-claimer/src/listener.rs
offchain/rollups-events/src/broker/mod.rs

While here, improve docs
Refers to #551

Log duplicate addresses on experimental multi dapp claimer

---

build/compose-devnet.yaml

When working on #535, testing worked fine, but there's actually a chance that when initiating through docker that the node starts before the cli has a chance to run migrations, thus creating an error and shutting down.
This simple PR fixes that.

Fix: compose devnet check cli

---

internal/repository/validator.go
internal/repository/validator_test.go

Since epochs with no inputs won't be stored in the database, the block range between epochs might be disjointed, breaking this function. Filtering results based on the epoch index alone will be enough.

fix(repository): get the previous epoch by index
